stage: prod
frontendHost: 'https://www.dojoscoreboard.com'
mobileHost: 'exp://127.0.0.1:8081/--/'
discordFindGameChannelId: '972163822850814022'
discordPrivateGuildId: '951958534113886238'
discordPublicGuildId: '419042970558398469'
monthlySubscriptionPriceId: 'price_1OJIsJGilmvijaecExwiQfAX'
yearlySubscriptionPriceId: 'price_1OJIsJGilmvijaec2sL831rf'
domainCertificateArn: 'arn:aws:acm:us-east-1:717403174598:certificate/15fcadca-b240-416d-a905-08572cddd572'
