# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: chess-dojo-scheduler
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

plugins:
  - serverless-plugin-custom-roles

provider:
  name: aws
  stage: ${file(./config.yml):stage}
  runtime: go1.x
  region: us-east-1
  environment:
    stage: ${opt:stage, self:provider.stage}
    frontendHost: ${file(./config.yml):frontendHost}
  httpApi:
    cors: true
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt CognitoUserPool.ProviderURL
        audience:
          - Ref: UserClient

package:
  individually: true
  patterns:
    - '!./**'

functions:
  ######### User Endpoints ###############

  createUser:
    handler: bin/user/create
    package:
      patterns:
        - ./bin/user/create
    events:
      - cognitoUserPool:
          pool: ${opt:stage, self:provider.stage}-chess-dojo-scheduler-auth-pool
          trigger: PostConfirmation
          existing: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt UsersTable.Arn

resources:
  Resources:
    ######### Cognito Resources ###############

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${opt:stage, self:provider.stage}-chess-dojo-scheduler-auth-pool
        UsernameConfiguration:
          CaseSensitive: false
        AliasAttributes:
          - email
        MfaConfiguration: OFF
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        AutoVerifiedAttributes: ['email']

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${opt:stage, self:provider.stage}-chess-dojo-scheduler-auth-client
        GenerateSecret: false
        UserPoolId: { Ref: CognitoUserPool }
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthFlows:
          - code
        AllowedOAuthScopes:
          - openid
          - email
          - profile
        CallbackURLs:
          - ${file(./config.yml):frontendHost}
        LogoutURLs:
          - ${file(./config.yml):frontendHost}
        SupportedIdentityProviders:
          - Google
        AccessTokenValidity: 24
        IdTokenValidity: 24

    UserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        UserPoolId: { Ref: CognitoUserPool }
        Domain: user-pool-domain-${opt:stage, self:provider.stage}-chess-dojo-scheduler

    UserPoolIdentityProvider:
      Type: AWS::Cognito::UserPoolIdentityProvider
      Properties:
        UserPoolId: { Ref: CognitoUserPool }
        ProviderName: 'Google'
        ProviderDetails:
          client_id: ${file(./oauth.yml):client_id}
          client_secret: ${file(./oauth.yml):client_secret}
          authorize_scopes: 'profile email openid'
        ProviderType: 'Google'
        AttributeMapping:
          email: 'email'
          name: 'name'
          username: 'sub'
          email_verified: 'email_verified'

    ######### End Cognito Resources ###############

    ######### DynamoDB Resources ##################

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${opt:stage, self:provider.stage}-users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
